version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: 'database'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run dev
    volumes:
      - ./src:/home/node/app/src
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - ${NODE_PORT}:${NODE_PORT}
