version: '3.7'

services:
  pg:
    image: postgres:17.6
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    user: "0"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run --watch src/index.ts
    volumes:
      - ./src:/home/bun/app/src
    env_file:
      - .env
    depends_on:
      - pg
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    user: "0"
