name: CI

on:
  push:
    branches: [main]
    paths:
      - package.json
      - bun.lock
      - src/**
      - mikro-orm.config.ts
      - .prettierrc
      - .prettierignore
      - .eslintrc.js
      - .eslintignore
      - tsconfig.build.json
      - tsconfig.json
      - .github/**

  pull_request:
    branches: [main]
    paths:
      - package.json
      - bun.lock
      - src/**
      - mikro-orm.config.ts
      - .prettierrc
      - .prettierignore
      - .eslintrc.js
      - .eslintignore
      - tsconfig.build.json
      - tsconfig.json
      - .github/**

jobs:
  lint:
    uses: ./.github/workflows/ci-lint-check.yml
  format:
    uses: ./.github/workflows/ci-format-check.yml
  test:
    uses: ./.github/workflows/ci-unit-test.yml
